# Generated by Django 3.0.8 on 2021-07-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
