# Generated by Django 3.0.8 on 2021-07-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0003_category_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
